### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by oliverfindl** [oliverfindl/node-spotilocal#1]
Not working since 2018-07-19 due to Spotify app update.

> Remote control of Spotify’s desktop app has been deprecated in favour of full track playback in the browser. [[source](https://developer.spotify.com/community/news/2018/07/19/new-updates-to-spotify-play-button/)]

**Comment by pillarshadow** [comment]
Is there no way to control spotify via node js now?

**Comment by oliverfindl** [comment]
Hello, you can use [Spotify Web API](https://developer.spotify.com/documentation/web-api/), but user authorization is required.

**Comment by oliverfindl** [comment]
This repo is now deprecated and archived.
